In [2]:
import numpy as np

In [3]:
a=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,53]])


In [4]:
print(a)

[[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 53]]


In [5]:
print(a[1:3,1:3])

[[35 36]
 [43 47]]


In [6]:
print(a[2: ,1:])

[[43 47 50]
 [51 52 53]]


In [7]:
print(a[0:2,2:])

[[24 25]
 [36 40]]


In [8]:
import pandas as pd

In [12]:
x=pd.DataFrame({'rollno':[101,102,103],'name':['priya','riya','siya']},index=[0,1,2],columns=("rollno","name"))

In [13]:
print(x)

   rollno   name
0     101  priya
1     102   riya
2     103   siya


In [15]:
x.head(2)

rollno   name
0     101  priya
1     102   riya

In [26]:
x.describe()

<class 'AttributeError'>: 'dict' object has no attribute 'describe'

In [17]:
x.tail(2)

rollno  name
1     102  riya
2     103  siya

In [18]:
x={'rollno':[101,102,103],'name':['siya','priya','riya']}

In [19]:
type(x)

dict

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("ipl.csv")

In [9]:
df.head(5)

team1                        team2  match_date  \
0  Royal Challengers Bangalore        Kolkata Knight Riders  2008-04-18   
1              Kings XI Punjab          Chennai Super Kings  2008-04-19   
2             Delhi Daredevils             Rajasthan Royals  2008-04-19   
3               Mumbai Indians  Royal Challengers Bangalore  2008-04-20   
4        Kolkata Knight Riders              Deccan Chargers  2008-04-20   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

  player_of_match                                       venue        city  \
0     BB McCullum                       M Chinnaswamy Stadium   Bangalore   
1      MEK Hussey  Punjab Cricket Association Stadium, Mohali  Chandigarh   
2     MF Maharoof                            Feroz Shah Kotla       Delhi   
3      MV Boucher                            Wankhede Stadium      Mumbai   
4       DJ Hussey                                Eden Gardens     Kolkata   

                                       team1_players  \
0  R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...   
1  K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...   
2  G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...   
3  L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...   
4  WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...   

                                       team2_players  season  match_number  \
0  SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...       1             1   
1  PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...       1             2   
2  T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...       1             3   
3  S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...       1             4   
4  AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...       1             5   

  match_type   result  result_margin  target_runs  target_overs super_over  
0     League     runs          140.0        223.0          20.0          N  
1     League     runs           33.0        241.0          20.0          N  
2     League  wickets            9.0        130.0          20.0          N  
3     League  wickets            5.0        166.0          20.0          N  
4     League  wickets            5.0        111.0          20.0          N

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   team1            1169 non-null   object 
 1   team2            1169 non-null   object 
 2   match_date       1169 non-null   object 
 3   toss_winner      1169 non-null   object 
 4   toss_decision    1169 non-null   object 
 5   winner           1146 non-null   object 
 6   player_of_match  1169 non-null   object 
 7   venue            1169 non-null   object 
 8   city             1118 non-null   object 
 9   team1_players    1169 non-null   object 
 10  team2_players    1169 non-null   object 
 11  season           1169 non-null   int64  
 12  match_number     1169 non-null   int64  
 13  match_type       1169 non-null   object 
 14  result           1169 non-null   object 
 15  result_margin    1146 non-null   float64
 16  target_runs      1163 non-null   float64
 17  target_overs  

In [11]:
df.describe()

season  match_number  result_margin  target_runs  target_overs
count  1169.000000   1169.000000    1146.000000  1163.000000   1163.000000
mean      9.687767     33.359281      17.364747   167.253654     19.768014
std       5.253100     19.430749      21.919255    34.222771      1.542583
min       1.000000      1.000000       1.000000    43.000000      5.000000
25%       5.000000     17.000000       6.000000   147.000000     20.000000
50%      10.000000     33.000000       8.000000   167.000000     20.000000
75%      15.000000     49.000000      20.000000   188.000000     20.000000
max      18.000000     76.000000     146.000000   288.000000     20.000000

In [13]:
df.index

RangeIndex(start=0, stop=1169, step=1)

In [14]:
df.shape

(1169, 19)

In [17]:
df.columns.names

FrozenList([None])

In [18]:
df.columns.values

array(['team1', 'team2', 'match_date', 'toss_winner', 'toss_decision',
       'winner', 'player_of_match', 'venue', 'city', 'team1_players',
       'team2_players', 'season', 'match_number', 'match_type', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over'],
      dtype=object)

In [19]:
df.dtypes

team1               object
team2               object
match_date          object
toss_winner         object
toss_decision       object
winner              object
player_of_match     object
venue               object
city                object
team1_players       object
team2_players       object
season               int64
match_number         int64
match_type          object
result              object
result_margin      float64
target_runs        float64
target_overs       float64
super_over          object
dtype: object

In [20]:
df.shape

(1169, 19)

In [21]:
df.columns

Index(['team1', 'team2', 'match_date', 'toss_winner', 'toss_decision',
       'winner', 'player_of_match', 'venue', 'city', 'team1_players',
       'team2_players', 'season', 'match_number', 'match_type', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over'],
      dtype='object')

In [22]:
df.iloc[200]

team1                                                Deccan Chargers
team2                                                 Mumbai Indians
match_date                                                2011-04-24
toss_winner                                          Deccan Chargers
toss_decision                                                  field
winner                                                Mumbai Indians
player_of_match                                           SL Malinga
venue                      Rajiv Gandhi International Stadium, Uppal
city                                                       Hyderabad
team1_players      S Sohal, S Dhawan, KC Sangakkara, CL White, B ...
team2_players      DJ Jacobs, SR Tendulkar, AT Rayudu, KA Pollard...
season                                                             4
match_number                                                      26
match_type                                                    League
result                            

In [23]:
df.toss_winner.iloc[200]

'Deccan Chargers'

In [24]:
df.iloc[:,2:7]

match_date                  toss_winner toss_decision  \
0     2008-04-18  Royal Challengers Bangalore         field   
1     2008-04-19          Chennai Super Kings           bat   
2     2008-04-19             Rajasthan Royals           bat   
3     2008-04-20               Mumbai Indians           bat   
4     2008-04-20              Deccan Chargers           bat   
...          ...                          ...           ...   
1164  2025-05-27  Royal Challengers Bengaluru         field   
1165  2025-05-29  Royal Challengers Bengaluru         field   
1166  2025-05-30               Mumbai Indians           bat   
1167  2025-06-01                 Punjab Kings         field   
1168  2025-06-03                 Punjab Kings         field   

                           winner player_of_match  
0           Kolkata Knight Riders     BB McCullum  
1             Chennai Super Kings      MEK Hussey  
2                Delhi Daredevils     MF Maharoof  
3     Royal Challengers Bangalore      MV Boucher  
4           Kolkata Knight Riders       DJ Hussey  
...                           ...             ...  
1164  Royal Challengers Bengaluru       JM Sharma  
1165  Royal Challengers Bengaluru   Suyash Sharma  
1166               Mumbai Indians       RG Sharma  
1167                 Punjab Kings         SS Iyer  
1168  Royal Challengers Bengaluru       KH Pandya  

[1169 rows x 5 columns]

In [25]:
df.iloc[:101,1:6]

team2  match_date                  toss_winner  \
0          Kolkata Knight Riders  2008-04-18  Royal Challengers Bangalore   
1            Chennai Super Kings  2008-04-19          Chennai Super Kings   
2               Rajasthan Royals  2008-04-19             Rajasthan Royals   
3    Royal Challengers Bangalore  2008-04-20               Mumbai Indians   
4                Deccan Chargers  2008-04-20              Deccan Chargers   
..                           ...         ...                          ...   
96         Kolkata Knight Riders  2009-05-12  Royal Challengers Bangalore   
97                Mumbai Indians  2009-05-12              Kings XI Punjab   
98              Delhi Daredevils  2009-05-13              Deccan Chargers   
99           Chennai Super Kings  2009-05-14          Chennai Super Kings   
100             Rajasthan Royals  2009-05-14             Rajasthan Royals   

    toss_decision                       winner  
0           field        Kolkata Knight Riders  
1             bat          Chennai Super Kings  
2             bat             Delhi Daredevils  
3             bat  Royal Challengers Bangalore  
4             bat        Kolkata Knight Riders  
..            ...                          ...  
96          field  Royal Challengers Bangalore  
97            bat               Mumbai Indians  
98          field             Delhi Daredevils  
99            bat  Royal Challengers Bangalore  
100           bat             Rajasthan Royals  

[101 rows x 5 columns]

In [26]:
df.iloc[:5,4:6]

toss_decision                       winner
0         field        Kolkata Knight Riders
1           bat          Chennai Super Kings
2           bat             Delhi Daredevils
3           bat  Royal Challengers Bangalore
4           bat        Kolkata Knight Riders

In [27]:
df.target_runs.min()

np.float64(43.0)