In [2]:
import numpy as np

In [3]:
a=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,53]])


In [4]:
print(a)

[[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 53]]


In [5]:
print(a[1:3,1:3])

[[35 36]
 [43 47]]


In [6]:
print(a[2: ,1:])

[[43 47 50]
 [51 52 53]]


In [7]:
print(a[0:2,2:])

[[24 25]
 [36 40]]


In [8]:
import pandas as pd

In [12]:
x=pd.DataFrame({'rollno':[101,102,103],'name':['priya','riya','siya']},index=[0,1,2],columns=("rollno","name"))

In [13]:
print(x)

   rollno   name
0     101  priya
1     102   riya
2     103   siya


In [15]:
x.head(2)

rollno   name
0     101  priya
1     102   riya

In [24]:
pd.iloc(x[0:1,1:3])

<class 'AttributeError'>: module 'pandas' has no attribute 'iloc'

In [16]:
x.describe()

rollno
count     3.0
mean    102.0
std       1.0
min     101.0
25%     101.5
50%     102.0
75%     102.5
max     103.0

In [17]:
x.tail(2)

rollno  name
1     102  riya
2     103  siya

In [18]:
x={'rollno':[101,102,103],'name':['siya','priya','riya']}

In [19]:
type(x)

dict

In [23]:
pd.iloc(x[0:1,1:3])

<class 'AttributeError'>: module 'pandas' has no attribute 'iloc'